amundsen-io/amundsencommon

- README.md
- setup.py
Almost too little to warrant a PR, but hey!
> Add python_requires to setup.py

- PULL_REQUEST_TEMPLATE.md
Removed `SQUASH COMMITS` from the PR template
> Removed `SQUASH COMMITS` from the PR template

- amundsen_common/models/table.py
- amundsen_common/models/user.py
- requirements.txt
- setup.cfg
- setup.py
Add table and user models from metadata builder to the common repo. Increase version number.
None, just adding models.
None.
> add table, user models to common

- amundsen_common/models/popular_table.py
- setup.py
Add the popular table model as well, to share between metadatastore and the frontend.
Upped the version 0.5 optimistically that my other PR will get merged, otherwise we'll need to bump this version down.
none, model change only.
none, model change only.
> add popular tables model

- setup.py
Fix Markdown formatting on https://pypi.org/project/amundsen-common/ as per https://dustingram.com/articles/2018/03/16/markdown-descriptions-on-pypi/
None - only a doc formatting change. 
None - only a doc formatting change. 
> Fix pypi markdown rendering

- amundsen_common/models/table.py
- setup.py
Relax all requirements for all application parameters but "id"
None
None
> make most application parameters optional

- README.md
- setup.py
Matching the Python version requirement with other micro-services.
Integration tested.
README.md
> Amundsen common to require Python 3.6 or higher

- requirements.txt
- setup.py
Adds attrs, marshmallows to requirements. Obviates the need to add them in things that use amundsen common.
None, requirements only.
None, requirements only.
> add attrs, marshmallows to requirements

- amundsen_common/models/user.py
- setup.py
Based no the discussion in the https://github.com/lyft/amundsen/issues/34, we'd like to have a unique identifier for the users, that can be used across the different repos for Amundsen. 
NA
NA
> Adds an extra optional field to support User ID

- amundsen_common/models/user.py
- setup.py
Add role_name to user model.
_What tests did you add or modify and why? If no tests were added or modified, explain why. Remove this line_
_What documentation did you add or modify and why? Add any relevant links then remove this line_
> Add role name to user model

- amundsen_common/models/table.py
- setup.py
In reference to the discussion [here](https://github.com/lyft/amundsenfrontendlibrary/pull/407#discussion_r405041682), this will set the default value of `programmatic_descriptions` as an empty list. 
NA
NA
> Fixes the default value of `programmatic_descriptions` attribute

- amundsen_common/models/dashboard.py
- setup.py
Based on the discussion
_What tests did you add or modify and why? If no tests were added or modified, explain why. Remove this line_
_What documentation did you add or modify and why? Add any relevant links then remove this line_
> Add product to summary

- amundsen_common/models/popular_table.py
- amundsen_common/models/table.py
- setup.py
Add:
- TableSummary class with schema description
Update:
- PopularTable to be deprecated -- added docstring.
N/A
> TableSummary class with schema description

- amundsen_common/models/user.py
- setup.py
Added `other_key_values` into User model to support non-general use cases (e.g: `id` of other system such as Mode Analytics)
N/A
N/A
> feat: Added other_key_values into User model

- setup.py
To pick up the latest report URL changes. 
_What tests did you add or modify and why? If no tests were added or modified, explain why. Remove this line_
_What documentation did you add or modify and why? Add any relevant links then remove this line_
> chore: Update version to pick up report url changes

- amundsen_common/models/table.py
- setup.py
Changed badges field on Table model to contain badges model.
> feat: Table model badges field update

- amundsen_common/models/table.py
- setup.py
> chore: bump version

- amundsen_common/models/index_map.py
Sync its mapping to databuilder's change(https://github.com/amundsen-io/amundsendatabuilder/pull/373#event-3794658228)
> fix: Update elasticsearch mapping to sync with databuilder's mapping

- amundsen_common/models/index_map.py
Add dashboard index mapping to model
> refactor: Add dashboard index mapping

- amundsen_common/models/table.py
- setup.py
Added badges field to Column model in table.
> feat: added badges field (optional) to column in table model

- setup.py
> chore: fix setup.py

- setup.py
> chore: set a range for deps

- amundsen_common/models/dashboard.py
- setup.py
> feat: add chart to dashboard model

- amundsen_common/models/dashboard.py
- setup.py
> fix: fix import

- Makefile
> fix: enable flake8 and mypy in CI

- README.md
- amundsen_common/models/table.py
> chore: clean up unused badge and deprecated models

- amundsen_common/models/index_map.py
- setup.py
databuilder will refer the index map defined in common (https://github.com/amundsen-io/amundsendatabuilder/pull/385/files). So we should update the dashboard map here as well.
> feat: add chart into common ES index map

- setup.py
Was adding dependency link incorrectly on setup.py file according to https://stackoverflow.com/questions/26061610/pip-install-dependency-links
> fix: marshmallow dependency link

- amundsen_common/models/index_map.py
- setup.py
Signed-off-by: tianru zhou <tianr.zhou@gmail.com>
make column names search case insensitive
> fix: make column names searchable by lowercase

- amundsen_common/models/index_map.py
- setup.py
Signed-off-by: tianru zhou <tianr.zhou@gmail.com>
> fix: fix table index map bug

- .github/workflows/monthly_release.yml
- .github/workflows/publish_release.yml
- setup.cfg
Added github action that automates releases using python-semantic-release, creates a PR, and publishes new version.
> chore: added action for automated release

- setup.py
added var for version outside of setup()
> fix: moved version declaration

- setup.py
Get dependency conflict when bumping amundsen-common to latest version on amundsenmetadatalibrary.
> fix: marshmallow and marshmallow-annotations causing issues

- amundsen_common/models/lineage.py
- setup.py
> fix: add meta class to lineage schemas
